# -*- coding: utf-8 -*-
summaryDic = {
    "◎译　　名": "chineseName",
    "◎译　　 名": "chineseName",
    "◎片　　名": "movieName",
    "◎片　　 名": "movieName",
    "◎又　　名": "anotherName",
    "◎年　　代": "year",
    "◎年　　 代": "year",
    "◎产　　地": "area",
    "◎类　　别": "type",
    "◎类　　型": "type",
    "◎电影类型": "type",
    "◎语　　言": "language",
    "◎字　　幕": "subtitle",
    "◎上映日期": "releaseTime",
    "◎IMDb评分": "imdbScore",
    "◎IMDB评分": "imdbScore",
    "◎IMBD评分": "imdbScore",
    "◎iMDB评分": "imdbScore",
    "◎豆瓣评分": "dbScore",
    "◎文件格式": "fileFormat",
    "◎视频尺寸": "videoSize",
    "◎文件大小": "fileSize",
    "◎片　　长": "videoTime",
    "◎导　　演": "director",
    "◎主　　演": "mainActor",
    "◎演　　员": "mainActor",
    "◎编　　剧": "editor",
    "◎简　　介": "summary",
    "◎简  介": "summary",
    "◎簡　　介": "summary",
    "◎IMDb链接": "imdbLink",
    "◎获奖情况": "awardSituation",
    "◎获奖记录": "awardSituation",
    "◎ 获奖情况": "awardSituation",
    "◎主要奖项": "awardSituation",
    "◎国　　家": "country",
    "◎国　　 家": "country",
    "◎地　　区": "region",
    "◎集　　数": "episode",
    "◎BT之家整理": "btHome",
    "◎幕后花絮": "scenes",
    "◎花　　絮": "scenes",
    "◎电影花絮": "scenes",
    "◎关于电影": "aboutMovie"
}
